- name: Install Python setup tools
  apt: name="{{item}}" state=present
  with_items:
    - python3-pip
    - python3-dev
    - libpq-dev
    - postgresql
    - postgresql-contrib
    - nginx
  become: true
  become_method: sudo

- name: Create PostgreSQL database and user
